name: 'Apply branch protection to the master'
description: 'This action adds branch protection to the Master branch'
inputs:
  mytoken:  # id of input
    description: 'Token'
    required: false
    default: ${{secrets.ORG_ADMIN_PAT}}
  required_approvers:
    description: 'Int: Required number of approvers'
    required: false
    default: '1'
runs:
  using: 'node12'
  main: 'index.js'