name: 'Commit Notify'
description: 'When a commit is made, it creates an issue and assigns to repo owner'
# inputs:
#   who-to-greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'