on:
  push:

jobs:
  commit-notify:
    runs-on: ubuntu-latest
    name: notify when a master commit is made
    steps:
    - name: Run commit notify
      uses: rohitnb/js-action-one@master
      with:
        mytoken: ${{secrets.GITHUB_TOKEN}}