name: Update branch protections
on:
  workflow_dispatch:

jobs:
  create_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Update branch protections
      env:
        REVIEWER_COUNT: 2
      run: |
        curl --location --request PUT 'https://api.github.com/repos/${{ github.repository }}/branches/master/protection' \
        --header 'Accept: application/vnd.github.luke-cage-preview+json' \
        --header 'Authorization: token ${{ secrets.ORG_ADMIN_PAT }}' \
        --header 'Content-Type: application/json' \
        --data-raw '{
        "required_status_checks": null, 
        "enforce_admins": false, 
        "required_pull_request_reviews": 
        {
          "dismiss_stale_reviews": false,
          "require_code_owner_reviews": false,
          "required_approving_review_count": ${{env.REVIEWER_COUNT}}
        }, 
        "restrictions": null
        }'

